### ISSUE TITLE
Error deploying to Vercel

### ISSUE THREAD

**Issue by pwnllc** [pilotpirxie/devcaptcha#4]
When I try to deploy it to Vercel, I get the following error:
`
[00:03:43.776] $ webpack --config webpack.production.config.js
[00:03:46.552] /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:133
[00:03:46.552] 		if(isError) throw e;
[00:03:46.552] 		            ^
[00:03:46.552] 
[00:03:46.552] Error: error:0308010C:digital envelope routines::unsupported
[00:03:46.552]     at new Hash (node:internal/crypto/hash:69:19)
[00:03:46.552]     at Object.createHash (node:crypto:133:10)
[00:03:46.553]     at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
[00:03:46.553]     at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:417:16)
[00:03:46.553]     at handleParseError (/vercel/path0/node_modules/webpack/lib/NormalModule.js:471:10)
[00:03:46.553]     at /vercel/path0/node_modules/webpack/lib/NormalModule.js:503:5
[00:03:46.553]     at /vercel/path0/node_modules/webpack/lib/NormalModule.js:358:12
[00:03:46.553]     at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[00:03:46.553]     at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[00:03:46.553]     at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[00:03:46.553]     at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[00:03:46.553]     at context.callback (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[00:03:46.553]     at makeSourceMapAndFinish (/vercel/path0/node_modules/ts-loader/dist/index.js:93:5)
[00:03:46.554]     at successLoader (/vercel/path0/node_modules/ts-loader/dist/index.js:74:9)
[00:03:46.554]     at Object.loader (/vercel/path0/node_modules/ts-loader/dist/index.js:25:5)
[00:03:46.554]     at LOADER_EXECUTION (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
[00:03:46.554]     at runSyncOrAsync (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
[00:03:46.554]     at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
[00:03:46.554]     at Array.<anonymous> (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[00:03:46.554]     at Storage.finished (/vercel/path0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
[00:03:46.554]     at /vercel/path0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
[00:03:46.554]     at /vercel/path0/node_modules/graceful-fs/graceful-fs.js:123:16
[00:03:46.555]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
[00:03:46.556]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[00:03:46.556]   library: 'digital envelope routines',
[00:03:46.556]   reason: 'unsupported',
[00:03:46.556]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[00:03:46.556] }
[00:03:46.556] 
[00:03:46.556] Node.js v18.17.1
[00:03:46.578] error Command failed with exit code 1.
[00:03:46.578] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[00:03:46.595] Error: Command "yarn run build" exited with 1`

**Comment by pwnllc** [comment]
[https://i.imgur.com/cWKCtXd.png](https://i.imgur.com/cWKCtXd.png) for the colourful version
